### ISSUE TITLE
Add a theme toggle in then app 

### ISSUE THREAD

**Issue by MrBlackGhostt** [MrBlackGhostt/nextTube#1]
We want to enhance the user experience by adding a theme toggle feature to switch between light and dark modes. This will provide users with the option to choose their preferred theme for the site.

Requirements:

    Add a theme toggle button in the header or navbar.
    Implement light and dark themes using CSS or a styling library.
    Ensure that the theme preference is saved in local storage, so it persists across sessions.
    The toggle should smoothly transition between themes for a better user experience.
    Update relevant components and styles to support both themes.

**Comment by ashishmohanty10** [comment]
I can use shandcn components right?

**Comment by ashishmohanty10** [comment]
https://github.com/user-attachments/assets/51d437fa-efcc-4c79-94c8-535c9d3275ae


/assign

Fix #1

should I raise a pull request or anyone is working on it?

**Comment by MrBlackGhostt** [comment]
no one working you can make the pull request on Develop branch

**Comment by ashishmohanty10** [comment]
and one more thing instead of giving direct color attributes to icon its better to use tailwind classes so that we can easily implement dark and light mode

**Comment by MrBlackGhostt** [comment]
yes we can

**Comment by MrBlackGhostt** [comment]
@ashishmohanty10 thanks for adding the theme
